## Append samples you want in your CSV to this file as resources ##
resources:
- core_v1_configmap.yaml
- kubetemplater.io_v1alpha1_kubetemplate.yaml
- kubetemplater.io_v1alpha1_kubetemplatepolicy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
