{{- if and .Values.webhook.enabled (eq .Values.webhook.certificateMode "cert-manager") }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kubetemplater.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetemplater.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kubetemplater.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetemplater.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "kubetemplater.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "kubetemplater.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.webhook.certManager.issuerName }}
    name: {{ .Values.webhook.certManager.issuerName }}
    {{- else }}
    name: {{ include "kubetemplater.fullname" . }}-selfsigned-issuer
    {{- end }}
    kind: {{ .Values.webhook.certManager.issuerKind }}
  secretName: {{ include "kubetemplater.fullname" . }}-webhook-server-cert
{{- end }}
