apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubetemplater-metrics-auth-rolebinding
  annotations:
    helm.sh/resource-policy: keep-on-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetemplater-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubetemplater.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
