apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetemplater-metrics-reader
  annotations:
    helm.sh/resource-policy: keep-on-delete
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
