apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubetemplater
  name: kubetemplater-manager-rolebinding
  annotations:
    helm.sh/resource-policy: keep-on-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetemplater-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubetemplater.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
