{{- if and .Values.webhook.enabled (eq .Values.webhook.certificateMode "self-signed") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubetemplater.fullname" . }}-cert-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetemplater.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - {{ include "kubetemplater.fullname" . }}-webhook-cert
  verbs:
  - get
  - update
  - patch
{{- end }}
