{{- if and .Values.webhook.enabled (eq .Values.webhook.certificateMode "self-signed") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubetemplater.fullname" . }}-cert-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetemplater.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubetemplater.fullname" . }}-cert-manager
subjects:
- kind: ServiceAccount
  name: {{ include "kubetemplater.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
