apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubetemplater
  name: kubetemplater-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubetemplater-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kubetemplater.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
