{{- if and .Values.webhook.enabled (eq .Values.webhook.certificateMode "self-signed") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubetemplater.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetemplater.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
{{- end }}
