{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetemplater.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetemplater.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.webhook.service.port }}
    targetPort: {{ .Values.webhook.service.targetPort }}
    protocol: TCP
    name: https
  selector:
    {{- include "kubetemplater.selectorLabels" . | nindent 4 }}
{{- end }}
