{{- if and .Values.webhook.enabled (eq .Values.webhook.certificateMode "manual") }}
{{- if and .Values.webhook.certificate.tlsCert .Values.webhook.certificate.tlsKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubetemplater.fullname" . }}-webhook-manual-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubetemplater.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webhook.certificate.tlsCert }}
  tls.key: {{ .Values.webhook.certificate.tlsKey }}
{{- end }}
{{- end }}
